### ISSUE TITLE
pbalign Time

### ISSUE THREAD

**Issue by sudhirjadhao** [PacificBiosciences/pbalign#14]
I have 450 mb assembly I am running pbalign to get h5 outputfile for quiver. pbalign have generated 130 GB sam file now its converting to h5  from last two days. h5 generated file size is 1.9 GB. Its still running. Can anyone tell me, how much time pbalign will take to finish job.

**Comment by ylipacbio** [comment]
How many bax.h5 files do you have? If you have many bax.h5 files, it is recommended to
  
* either use SMRTPortal, upload the assembly as reference sequence and then select the RS_Resequencing protocol, 
* or follow the [divide and conquer approach](https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign)

**Comment by sudhirjadhao** [comment]
Thank you for kind reply.
I have 114 bax.h5 file. Assembly is generated using falcon tool. you are suggesting me for genome finishing use RS_Resequencing  . output of this will be final assembly ?

**Comment by ylipacbio** [comment]
Yes, you may upload the assembled contigs as reference and run the RS_Resequencing pipeline on SMRTPortal. 

114 bax.h5 files are more than what pbalign is designed to handle.

**Comment by sudhirjadhao** [comment]
Thaks again,
which one will finish job early divide and conquer approach or SMRTPortal approach

**Comment by sudhirjadhao** [comment]
Hi I successfully  ran pbalign . Now I am trying to merge result with the help of  cmph5tools.py .
I successfully installed  cmph5tools.py. but when I am trying to run or tyring  cmph5tools.py --help it is giving below error

 cmph5tools.py --help
Traceback (most recent call last):
  File "/usr/local/bin/cmph5tools.py", line 4, in <module>
    __import__('pkg_resources').run_script('pbh5tools==0.8.0', 'cmph5tools.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1652, in run_script
    
  File "/usr/local/lib/python2.7/dist-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/cmph5tools.py", line 43, in <module>
    from pbh5tools.CmpH5Select import cmpH5Select
  File "/usr/local/lib/python2.7/dist-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg/pbh5tools/CmpH5Select.py", line 41, in <module>
    from pbcore.io import CmpH5Reader
  File "/usr/local/lib/python2.7/dist-packages/pbcore/io/__init__.py", line 38, in <module>
    from .align   import *
  File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/__init__.py", line 32, in <module>
    from BamIO          import *
  File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 45, in <module>
    from .PacBioBamIndex import PacBioBamIndex
  File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/PacBioBamIndex.py", line 40, in <module>
    from ._BamSupport import IncompatibleFile
  File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/_BamSupport.py", line 58, in <module>
    complementAscii = np.vectorize(ASCII_COMPLEMENT_MAP.get, otypes=[np.int8])
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1818, in __init__
    nin, ndefault = _get_nargs(pyfunc)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1750, in _get_nargs
    "failed to determine the number of arguments for %s" % (obj))
ValueError: failed to determine the number of arguments for <built-in method get of dict object at 0x26f55f0>


can you please tell me where I am going wrong
