### ISSUE TITLE
cmph5tools.py merge fails 

### ISSUE THREAD

**Issue by MichelMoser** [PacificBiosciences/pbalign#16]
Hi, 
I run into an error when trying to merge cmp.h5 files from 50 smrtcells. 

Here is what i did so far: 
With 50 smrtcells and a 1.4 Gb reference assembly, i tought of following your "divide and conquer" approach to polish the assembly (from MHAPcelera). 

I ran bpalign with --forQuiver option and created 50 .cmp.h5 files against the reference assembly. 
```
pbalign.py --verbose --forQuiver ../smrtcell_${SGE_TASK_ID}_*.fofn asmbly.fasta ${SGE_TASK_ID}.pbout.cmp.h5
```
Next i added Chemistry information to all .cmp.h5 files with. 
```
loadChemistry.py ../smrtcell_$i_*.fofn $i.pbout.cmp.h5
```

I tested quiver for only a single smrtcell .cmp.h5 if everything is formated well: 
```
quiver 1.pbout.cmp.h5 -r asmbly.fasta -o merg1.variants.gff -o merg1.consesus.fasta -o merg1.consensus.fastq --verbose
```

Everything ran through and files were created as expected. 

To merge all .cmp.h5 files, i used following command: 
```
cmph5tools.py --verbose merge --outFile merged_all.cmp.h5 smrtcell_1.pbout.cmp.h5 smrtcell_2.pbout.cmp.h5 ....
```

It ran for one day and then terminated with following error: 

```
2015-12-10 17:14:03,798 [INFO] No dataset: MovieInfo/Run
2015-12-10 17:14:03,799 [INFO] No dataset: MovieInfo/Exp
2015-12-10 17:14:06,386 [INFO] Skipping reference with no reads.
2015-12-10 17:14:07,005 [INFO] Skipping reference with no reads.
2015-12-10 17:14:07,368 [INFO] Skipping reference with no reads.
2015-12-10 17:14:07,551 [INFO] Skipping reference with no reads.
....
....
2015-12-11 22:20:00,826 [INFO] Skipping reference with no reads.
2015-12-11 22:20:03,946 [INFO] Skipping reference with no reads.
2015-12-11 22:20:04,440 [INFO] Skipping reference with no reads.
2015-12-11 22:20:04,441 [INFO] Skipping reference with no reads.
2015-12-11 22:20:07,535 [INFO] Skipping reference with no reads.
2015-12-11 22:20:07,728 [INFO] Skipping reference with no reads.
2015-12-11 22:20:07,729 [INFO] Skipping reference with no reads.
2015-12-11 22:20:08,099 [INFO] Skipping reference with no reads.
2015-12-11 22:20:08,100 [INFO] Skipping reference with no reads.
2015-12-11 22:20:08,456 [INFO] Skipping reference with no reads.
2015-12-11 22:20:10,814 [INFO] Skipping reference with no reads.
Traceback (most recent call last):
  File "/home/mmoser/PacBioScripts/pacbio_env/bin/cmph5tools.py", line 240, in <module>
    sys.exit(CmpH5ToolsRunner().start())
  File "/home/mmoser/PacBioScripts/pacbio_env/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/util/ToolRunner.py", line 112, in start
    return self.run()
  File "/home/mmoser/PacBioScripts/pacbio_env/bin/cmph5tools.py", line 182, in run
    cmpH5Merge(self.args.inCmps, self.args.outCmp, self.args.referencesFile)
  File "/home/mmoser/PacBioScripts/pacbio_env/lib/python2.7/site-packages/pbh5tools/CmpH5Merge.py", line 264, in cmpH5Merge
    alnGroup = {k:v for k,v in zip(cmpH5[fmt.ALN_GROUP_ID].value,
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-25hGxF/h5py/h5py/_objects.c:2574)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-25hGxF/h5py/h5py/_objects.c:2533)
  File "/home/mmoser/PacBioScripts/pacbio_env/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 193, in value
    return self[()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-25hGxF/h5py/h5py/_objects.c:2574)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-25hGxF/h5py/h5py/_objects.c:2533)
  File "/home/mmoser/PacBioScripts/pacbio_env/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 451, in __getitem__
    self.id.read(mspace, fspace, arr, mtype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-25hGxF/h5py/h5py/_objects.c:2574)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-25hGxF/h5py/h5py/_objects.c:2533)
  File "h5py/h5d.pyx", line 177, in h5py.h5d.DatasetID.read (/tmp/pip-build-25hGxF/h5py/h5py/h5d.c:3123)
  File "h5py/_proxy.pyx", line 126, in h5py._proxy.dset_rw (/tmp/pip-build-25hGxF/h5py/h5py/_proxy.c:1726)
RuntimeError: Unable to register datatype (Can't insert duplicate key)
```

Could you help me with that?

Versions used: 
```
pbalign 0.2.0.141024
cmph5tools.py 0.8.0
```

**Comment by ylipacbio** [comment]
pbalign is not designed to run 50 cells, please see this [wiki](https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign). Also please report cmph5tools issues to [pacbio cmph5tools repo](https://github.com/PacificBiosciences/pbh5tools/blob/master/bin/cmph5tools.py)

**Comment by RxLoutre** [comment]
Actually, this link does not (or no longer) exist... Quiet hard to figure out what is wrong as you didn't explained what it was about. As I see it, he didn't used 50 cells at the same time for pbalign, but each cells independently. Then tried to merge all the resulting cmp.h5 file using cmph5tools merge. 

For my own purpose, I need to do the same command as below, but with 10 cells instead of 50. What is the proper way to use pbalign/cmph5tools then ? I also keep having message wit "skipping reference with no reads". So I'm I going to face some troubles ?

Cheers,

Roxane

**Comment by ylipacbio** [comment]
`skipping reference with no reads` is shown when there is no reads mapping to a reference sequence. This does not mean you are going to face troubles unless you expect all reference sequence to have at least one read mapping to it.

For RSII and SMRTAnalysis v2.3, please see wiki for divide and conquer way of using pbalign.
https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-RSII-dataset-using-pbalign-and-blasr-in-SMRTAnalysis-2.3-(and-previous-version)

Or alternatively, you can convert BAX H5 files to BAM and use SMRTAnalysis 3.0+
https://github.com/PacificBiosciences/PacBioFileFormats/wiki/BAM-recipes
https://github.com/PacificBiosciences/pbalign/wiki/Work-with-sequel-BAM-files-and-datasets.
