### ISSUE TITLE
loadChemistry.py error

### ISSUE THREAD

**Issue by sudhirjadhao** [PacificBiosciences/pbalign#17]
I have generated cmp.h5 file using pbalign with option --forQuiver. Now I want to add chemistry to cmp.h5 file. I am trying to loadChemistry.py but its showing error.

loadChemistry.py --help
Traceback (most recent call last):
  File "/usr/local/bin/loadChemistry.py", line 9, in <module>
    load_entry_point('pbalign==0.2.0', 'console_scripts', 'loadChemistry.py')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
    
  File "/usr/local/lib/python2.7/dist-packages/pbalign/tools/loadChemistry.py", line 16, in <module>
    from pbcore.io import *
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/io/__init__.py", line 38, in <module>
    from .align   import *
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/io/align/__init__.py", line 32, in <module>
    from BamIO          import *
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/io/align/BamIO.py", line 45, in <module>
    from .PacBioBamIndex import PacBioBamIndex
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/io/align/PacBioBamIndex.py", line 40, in <module>
    from ._BamSupport import IncompatibleFile
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/io/align/_BamSupport.py", line 58, in <module>
    complementAscii = np.vectorize(ASCII_COMPLEMENT_MAP.get, otypes=[np.int8])
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1818, in __init__
    nin, ndefault = _get_nargs(pyfunc)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1750, in _get_nargs
    "failed to determine the number of arguments for %s" % (obj))
ValueError: failed to determine the number of arguments for <built-in method get of dict object at 0x2a60cc0>
bionivid-server@bionivid-PowerEdge-R910:/media/9759e2b0-edca-4aaa-a141-110bc7765ca3/Projects/Dr_Manu_Agrawal_Mungdal/quiver/LoadChemistry$ loadChemistry.py --help
Traceback (most recent call last):
  File "/usr/local/bin/loadChemistry.py", line 9, in <module>
    load_entry_point('pbalign==0.2.0', 'console_scripts', 'loadChemistry.py')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
    
  File "/usr/local/lib/python2.7/dist-packages/pbalign/tools/loadChemistry.py", line 16, in <module>
    from pbcore.io import *
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/io/__init__.py", line 38, in <module>
    from .align   import *
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/io/align/__init__.py", line 32, in <module>
    from BamIO          import *
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/io/align/BamIO.py", line 45, in <module>
    from .PacBioBamIndex import PacBioBamIndex
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/io/align/PacBioBamIndex.py", line 40, in <module>
    from ._BamSupport import IncompatibleFile
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/pbcore-1.2.4-py2.7.egg/pbcore/io/align/_BamSupport.py", line 58, in <module>
    complementAscii = np.vectorize(ASCII_COMPLEMENT_MAP.get, otypes=[np.int8])
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1818, in __init__
    nin, ndefault = _get_nargs(pyfunc)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1750, in _get_nargs
    "failed to determine the number of arguments for %s" % (obj))
ValueError: failed to determine the number of arguments for <built-in method get of dict object at 0x1833510>

Can you please help me to solve this error.

**Comment by ylipacbio** [comment]
chemistry info should have been already loaded automatically if --forQuiver is specified. No need to load chemistry info one more time.
