### ISSUE TITLE
pbalign --forQuiver flag does not output sorted .cmp.h5

### ISSUE THREAD

**Issue by afinit** [PacificBiosciences/pbalign#25]
According to the documentation, the `--forQuiver` flag is supposed to sort and repack the .cmp.h5 file that is output from pbalign. However this doesn't seem to be happening for me. Here is my pbalign command:

    $ pbalign --nproc 40 --forQuiver \
        m151209_163049_42157_c100923922550000001823194105121603_s1_p0.bas.h5 \
        falcon_assem.fa \
        falcon_assem_pbalign.cmp.h5

When I feed the output .cmp.h5 to quiver, I get an error saying the cmp.h5 isn't sorted:

    $ quiver -j 40 falcon_assem_pbalign.cmp.h5 \
        -r falcon_assem.fa \
        -o falcon_assem_quiver.gff \
        -o falcon_assem_quiver.fa
    Input CmpH5 file must be sorted.

As you can see, this directly contradicts the documentation. The `pbalign` and `quiver` versions I'm working with are from the `smrtsuite_3.0.2.170012.run` version of SMRT Suite.

    $ quiver --version
    1.1.0
    $ pbalign --version
    3.0

For now, I will see if I can manually sort this, but I would like to be able to run the `--forQuiver` flag and be able to use the output as input to `quiver`

**Comment by ylipacbio** [comment]
Would you please try the following command and check if pbalign exited successfully (return code 0)?
```
pbalign --verbose --forQuiver m151209_163049_42157_c100923922550000001823194105121603_s1_p0.bas.h5 falcon_assem.fa falcon_assem_pbalign.cmp.h5  --algorithmOptions=" -holeNumbers 1-5000"
```

Thanks

**Comment by afinit** [comment]
ImportError: ~/local/smrtsuite/install/smrtsuite-fromsrc_3.0.2.170012/bundles/smrttools/install/smrttools-fromsrc_3.0.2.170012/private/thirdparty/pythonpkgs/numpy/numpy_1.9.2/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS4_AsUnicodeEscapeString
    INFO:root:exiting with return code 1 in 56.48 sec.
    [INFO] 2016-04-04 14:08:57,743Z [root _pacbio_main_runner 94] exiting with return code 1 in 56.48 sec.

Indeed it exits with a return code 1. I didn't think about checking the verbose output, because every other time it exited with a non-zero status it let me know. I won't be able to follow this up until this afternoon, but it looks like the issue might be that the code is trying to use packages from my virtualenv and then numpy from the PacBio SMRT Suite python bundle. That's simply based on a cursory internet search though.

Thanks for the quick reply. I'll let you know if I come up with anything later.

**Comment by afinit** [comment]
I think the problem is solved. I installed `pbalign` from github and ran that instead of the SMRT Suite executable. This returns an exit code of 0.

I believe this is due to the use of packages from two different python installs: my virtualenv, and the install in the SMRT Suite. However this is out of my depth, so I've posted the full traceback below in case someone else can comment on this or has a similar issue.

    ImportError: ~/local/smrtsuite/install/smrtsuite-fromsrc_3.0.2.170012/bundles/smrttools/install/smrttools-fromsrc_3.0.2.170012/private/thirdparty/pythonpkgs/numpy/numpy_1.9.2/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS4_AsUnicodeEscapeString
    [ERROR] 2016-04-04 14:08:57,740Z [root Execute 67] SortService returned a non-zero exit status. Traceback (most recent call last):
      File "~/venv/falcon/bin/cmph5tools.py", line 43, in <module>
        from pbh5tools.CmpH5Select import cmpH5Select
      File "~/venv/falcon/lib/python2.7/site-packages/pbh5tools/CmpH5Select.py", line 38, in <module>
        import h5py as H5
      File "~/venv/falcon/lib/python2.7/site-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/__init__.py", line 23, in <module>
        from . import _conv
      File "h5py/h5t.pxd", line 14, in init h5py._conv (/tmp/easy_install-9OqCFX/h5py-2.5.0/h5py/_conv.c:7359)
      File "h5py/numpy.pxd", line 66, in init h5py.h5t (/tmp/easy_install-9OqCFX/h5py-2.5.0/h5py/h5t.c:20455)
      File "~/local/smrtsuite/install/smrtsuite-fromsrc_3.0.2.170012/bundles/smrttools/install/smrttools-fromsrc_3.0.2.170012/private/thirdparty/pythonpkgs/numpy/numpy_1.9.2/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
        from . import add_newdocs
      File "~/local/smrtsuite/install/smrtsuite-fromsrc_3.0.2.170012/bundles/smrttools/install/smrttools-fromsrc_3.0.2.170012/private/thirdparty/pythonpkgs/numpy/numpy_1.9.2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
        from numpy.lib import add_newdoc
      File "~/local/smrtsuite/install/smrtsuite-fromsrc_3.0.2.170012/bundles/smrttools/install/smrttools-fromsrc_3.0.2.170012/private/thirdparty/pythonpkgs/numpy/numpy_1.9.2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
        from .type_check import *
      File "~/local/smrtsuite/install/smrtsuite-fromsrc_3.0.2.170012/bundles/smrttools/install/smrttools-fromsrc_3.0.2.170012/private/thirdparty/pythonpkgs/numpy/numpy_1.9.2/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
        import numpy.core.numeric as _nx
      File "~/local/smrtsuite/install/smrtsuite-fromsrc_3.0.2.170012/bundles/smrttools/install/smrttools-fromsrc_3.0.2.170012/private/thirdparty/pythonpkgs/numpy/numpy_1.9.2/lib/python2.7/site-packages/numpy/core/__init__.py", line 6, in <module>
        from . import multiarray
    ImportError: ~/local/smrtsuite/install/smrtsuite-fromsrc_3.0.2.170012/bundles/smrttools/install/smrttools-fromsrc_3.0.2.170012/private/thirdparty/pythonpkgs/numpy/numpy_1.9.2/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS4_AsUnicodeEscapeString
    INFO:root:exiting with return code 1 in 56.48 sec.
    [INFO] 2016-04-04 14:08:57,743Z [root _pacbio_main_runner 94] exiting with return code 1 in 56.48 sec.

**Comment by ylipacbio** [comment]
Thanks for the update!
