### ISSUE TITLE
PBAlignRunner fails with "AttributeError: 'list' object has no attribute 'verbosity'"

### ISSUE THREAD

**Issue by bnbowman** [PacificBiosciences/pbalign#49]
Writing up a tool to align my HLA data by Barcode with PBalign, but PBAlignRunner is giving me an error.  I followed the instructions in the read me, and the following args:

['--maxHits', '1', '--nproc', '8', '--minAccuracy', 70, 'temp.subreadset.xml', u'/pbi/dept/secondary/siv/testdata/pblaa-unittest/P6-C4/HLA_ANRI/References/bc0--1.fasta', 'bc0--1.aln.bam']

Gives me the following error and traceback:

"""
Traceback (most recent call last):
  File "AlignByBarcode.py", line 78, in <module>
    res = alignSubreadSet( "temp.subreadset.xml", ref, output, NPROC, MIN_ACCURACY )
  File "AlignByBarcode.py", line 67, in alignSubreadSet
    exitCode = a.start()
  File "/pbi/dept/secondary/builds/3.2.0/smrttools/prebuilt/linux/x86-64/libc-2.5/gcc-4.8.4/ubuntu-1404/184210/smrttools-prebuilt_3.2.0.184210.installdir/private/pacbio/pythonpkgs/pbcore/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 94, in start
    self._setupLogging()
  File "/pbi/dept/secondary/builds/3.2.0/smrttools/prebuilt/linux/x86-64/libc-2.5/gcc-4.8.4/ubuntu-1404/184210/smrttools-prebuilt_3.2.0.184210.installdir/private/pacbio/pythonpkgs/pbcore/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 84, in _setupLogging
    if self.args.verbosity >= 2:
AttributeError: 'list' object has no attribute 'verbosity'
"""

**Comment by ylipacbio** [comment]
Close fixed issues.
