### ISSUE TITLE
blasr return a non-zero exit status

### ISSUE THREAD

**Issue by RxLoutre** [PacificBiosciences/pbalign#68]
Hi, sorry it's me again,

I've looked everywhere but couldn't find a post corresponding to my issue.

I've tried the following line : 

`pbalign --forQuiver /media/DATAPART1/pacbio_reads/raw_reads.fofn /media/loutre/SUZUKII/assembly_tries/canu/cleaned_names_canu3_suzukii.fasta /media/loutre/SUZUKII/assembly_tries/canu/canu3_polished/canu_polished.cmp.h5`

But I got this error : 

```
2017-02-03 12:54:31,634 [ERROR] BlasrService returned a non-zero exit status. [INFO] 2017-02-03T12:54:31 [blasr] started.
ERROR, the input reads files must include file extensions.
```

Here some info that might help : pbalign --versionpbalign :  0.2.0.138342 blasr -v : 1.3.1.142244
.fofn file look like this : 

```
/media/DATAPART1/pacbio_reads/run6/H01_1/Analysis_Results/m151220_023946_42237_c100942502550000001823214006101687_s1_p0.1.bax.h5
/media/DATAPART1/pacbio_reads/run6/H01_1/Analysis_Results/m151220_023946_42237_c100942502550000001823214006101687_s1_p0.2.bax.h5
```

Any idea of what is wrong with my command ?

Thanks for your help,

Roxane

**Comment by ylipacbio** [comment]
This error means that blasr could not find input file extension, probably indicating that there is something wrong (e.g., an unexpected space) with fofn file.

Can you run
```
pbalign -v --forQuiver /media/DATAPART1/pacbio_reads/run6/H01_1/Analysis_Results/m151220_023946_42237_c100942502550000001823214006101687_s1_p0.1.bax.h5 /media/loutre/SUZUKII/assembly_tries/canu/cleaned_names_canu3_suzukii.fasta  out.cmp.h5```

Or you may run the following command
```
pbalign -v -v --forQuiver /media/DATAPART1/pacbio_reads/raw_reads.fofn /media/loutre/SUZUKII/assembly_tries/canu/cleaned_names_canu3_suzukii.fasta /media/loutre/SUZUKII/assembly_tries/canu/canu3_polished/canu_polished.cmp.h5
```
which will show the BLASR command used in log and post the BLASR command shown here?

Thanks.

**Comment by RxLoutre** [comment]
Here the outputs of the two commands : 

First command : 

```
(smrtanalysis-2.3.0) Loutre:/opt/smrtanalysis/current/etc$ pbalign -v --forQuiver /media/DATAPART1/pacbio_reads/run6/H01_1/Analysis_Results/m151220_023946_42237_c100942502550000001823214006101687_s1_p0.1.bax.h5 /media/loutre/SUZUKII/assembly_tries/canu/cleaned_names_canu3_suzukii.fasta  out.cmp.h5
2017-02-07 08:08:56,068 [INFO] pbalign version: 0.2.0.138342
2017-02-07 08:08:56,122 [ERROR] Could not access output file /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/etc/out.cmp.h5.
Traceback (most recent call last):
  File "/opt/smrtanalysis/current/analysis/bin/pbalign", line 8, in <module>
    load_entry_point('pbalign==0.2.0', 'console_scripts', 'pbalign')()
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 289, in main
    return pbobj.start()
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 105, in start
    return self.run()
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 225, in run
    self._tempFileManager)
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 109, in _createAlignService
    service = BlasrService(args, fileNames, tempFileManager)
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbalign/alignservice/align.py", line 106, in __init__
    self._options.pulseFile)
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbalign/pbalignfiles.py", line 155, in SetInOutFiles
    self.SetOutputFileName(outputFileName)
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbalign/pbalignfiles.py", line 139, in SetOutputFileName
    self.outputFileName = checkOutputFile(outputFileName)
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbalign/utils/fileutil.py", line 250, in checkOutputFile
    raise IOError(errMsg + str(e))
IOError: Could not access output file /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/etc/out.cmp.h5.[Errno 13] Permission denied: '/opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/etc/out.cmp.h5'
```

The second one : 

```
(smrtanalysis-2.3.0) Loutre:/opt/smrtanalysis/current/etc$ pbalign -v -v --forQuiver /media/DATAPART1/pacbio_reads/raw_reads.fofn /media/loutre/SUZUKII/assembly_tries/canu/cleaned_names_canu3_suzukii.fasta /media/loutre/SUZUKII/assembly_tries/canu/canu3_polished/canu_polished.cmp.h5
2017-02-07 08:09:05,018 [INFO] pbalign version: 0.2.0.138342
2017-02-07 08:09:05,018 [DEBUG] Original arguments: ['-v', '-v', '--forQuiver', '/media/DATAPART1/pacbio_reads/raw_reads.fofn', '/media/loutre/SUZUKII/assembly_tries/canu/cleaned_names_canu3_suzukii.fasta', '/media/loutre/SUZUKII/assembly_tries/canu/canu3_polished/canu_polished.cmp.h5']
2017-02-07 08:09:07,552 [DEBUG] Parsed arguments considering configFile and algorithmOptions: Namespace(algorithm='blasr', algorithmOptions=None, byread=False, concordant=False, configFile=None, debug=False, filterAdapterOnly=False, forQuiver=True, hitPolicy='randombest', inputFileName='/media/DATAPART1/pacbio_reads/raw_reads.fofn', keepTmpFiles=False, maxDivergence=30, maxHits=10, metrics='DeletionQV,DeletionTag,InsertionQV,MergeQV,SubstitutionQV', minAccuracy=70, minAnchorSize=12, minLength=50, noSplitSubreads=False, nproc=8, outputFileName='/media/loutre/SUZUKII/assembly_tries/canu/canu3_polished/canu_polished.cmp.h5', profile=False, pulseFile=None, readType='standard', referencePath='/media/loutre/SUZUKII/assembly_tries/canu/cleaned_names_canu3_suzukii.fasta', regionTable=None, scoreCutoff=None, scoreFunction='alignerscore', seed=1, tmpDir='/scratch', useccs=None, verbosity=2)
2017-02-07 08:09:07,554 [INFO] BlasrService: Align reads to references using blasr.
2017-02-07 08:09:07,555 [DEBUG] BlasrService: Call "blasr /media/DATAPART1/pacbio_reads/raw_reads.fofn /media/loutre/SUZUKII/assembly_tries/canu/cleaned_names_canu3_suzukii.fasta -sam -out /tmp/tmpwC9pDi/jSKRj3.sam  -bestn 10 -minMatch 12  -nproc 8  -minSubreadLength 50 -minReadLength 50  -randomSeed 1  -placeRepeatsRandomly "
2017-02-07 08:09:07,583 [ERROR] BlasrService returned a non-zero exit status. [INFO] 2017-02-07T08:09:07 [blasr] started.
ERROR, the input reads files must include file extensions.
```

**Comment by RxLoutre** [comment]
Woups, really sorry. After investigating the fofn file (which were produced by SMRT Analysis) I found a line with, indeed, no file extension as it was a directory : 

`/media/DATAPART1/pacbio_reads/run6/H01_1/Analysis_Results`

I've deleted this line from my fofn file, and now pbalign run perfectly.

Thanks for helping me !
