### ISSUE TITLE
BamPostService returned BamPostService returned a non-zero exit status (Ubuntu 16.04)

### ISSUE THREAD

**Issue by fbemm** [PacificBiosciences/pbalign#75]
I am getting "BamPostService returned a non-zero exit status" with pbalign and Sequel data after a switch to Ubuntu 16.04.

smrtlink 4.0.0.190159+190159-190159-189856-189856-189856

[ERROR] 2017-06-02 18:13:08,484Z [pbalign.pbalignrunner _pacbio_main_runner 141] BamPostService returned a non-zero exit status. /bin/bash: /ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/thirdparty/python/python_2.7.9/binwrap/../../../../thirdparty/ncurses/ncurses_5.9/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/thirdparty/python/python_2.7.9/binwrap/../../../../thirdparty/ncurses/ncurses_5.9/lib/libtinfo.so.5: no version information available (required by /bin/bash)

Traceback (most recent call last):
  File "/ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/pacbio/pythonpkgs/pbcommand/lib/python2.7/site-packages/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/pacbio/pythonpkgs/pbalign/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 283, in args_runner
    return PBAlignRunner(args, output_dataset_type=output_dataset_type).start()
  File "/ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/pacbio/pythonpkgs/pbcore/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 112, in start
    return self.run()
  File "/ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/pacbio/pythonpkgs/pbalign/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 262, in run
    BamPostService(self.fileNames).run()
  File "/ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/pacbio/pythonpkgs/pbalign/lib/python2.7/site-packages/pbalign/bampostservice.py", line 134, in run
    sortedBamFile=self.outBamFile)
  File "/ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/pacbio/pythonpkgs/pbalign/lib/python2.7/site-packages/pbalign/bampostservice.py", line 100, in _sortbam
    Execute(self.name, cmd)
  File "/ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/pacbio/pythonpkgs/pbalign/lib/python2.7/site-packages/pbalign/utils/progutil.py", line 68, in Execute
    raise RuntimeError(errMsg)

RuntimeError: BamPostService returned a non-zero exit status. /bin/bash: /ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/thirdparty/python/python_2.7.9/binwrap/../../../../thirdparty/ncurses/ncurses_5.9/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /ebio/abt6_projects9/abt6_software/bin/smrtlink/install/smrtlink-fromsrc_4.0.0.190159+190159-190159-189856-189856-189856/bundles/smrttools/install/smrttools-fromsrc_4.0.0.190159/private/thirdparty/python/python_2.7.9/binwrap/../../../../thirdparty/ncurses/ncurses_5.9/lib/libtinfo.so.5: no version information available (required by /bin/bash)

[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  -@, --threads INT
             Set number of sorting and compression threads [1]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]

Any ideas?

**Comment by pb-dstucki** [comment]
The error in run-sat-services with
`/ncurses_5.9/lib/libtinfo.so.5: no version information available (required by /bin/bash)`
is likely caused by a particular behaviour of Ubuntu 16.04+ with the ncurses library.

Please use the following workaround (as the user who did the installation, usually "smrtanalysis"):

```
cd $SMRT_ROOT
mv ./current/bundles/smrttools/current/private/thirdparty/ncurses ./current/bundles/smrttools/current/private/thirdparty/ncurses.orig
mv ./current/bundles/smrtinub/current/private/thirdparty/ncurses ./current/bundles/smrtinub/current/private/thirdparty/ncurses.orig

```
stop and restart the SMRT Link services with 
```
$SMRT_ROOT/admin/bin/services-stop
$SMRT_ROOT/admin/bin/services-start
```

See also https://github.com/PacificBiosciences/SMRT-Link/issues/87
